-- Create learned_patterns table for AI self-learning
create table if not exists learned_patterns (
  id bigint generated by default as identity primary key,
  pattern_type text not null, -- e.g., 'er_range', 'keyword_ratio'
  condition text not null,    -- e.g., 'ER 2.0-3.0%', '구매 키워드 40% 이상'
  outcome text not null,      -- e.g., 'A급 이상', 'S급'
  confidence numeric not null, -- e.g., 85.5 (percentage)
  sample_size int not null,   -- e.g., 120 (number of samples used)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Unique constraint for upsert capability
  constraint learned_patterns_type_condition_key unique (pattern_type, condition)
);

-- Enable Row Level Security (RLS)
alter table learned_patterns enable row level security;

-- Create policy to allow public read (or authenticated read)
create policy "Enable read access for all users" on learned_patterns for select using (true);

-- Create policy to allow service_role only to insert/update
create policy "Enable insert for service_role only" on learned_patterns for insert with check (auth.role() = 'service_role');
create policy "Enable update for service_role only" on learned_patterns for update using (auth.role() = 'service_role');
